function imageViewer()
    MainFrm = figure('units','pixels',...
              'position',[1000 1000 1000 1000],...
              'menubar','none',...
              'name','Photoshop Program',...
              'numbertitle','off',...
              'resize','off');

    TitleFrm = axes ( ... 
        'position', [0, 0.8, 1, 0.2], ... 
        'color',    [0.9, 0.95, 1], ...
        'xtick',    [], ... 
        'ytick',    [], ...  
        'xlim',     [0, 1], ... 
        'ylim',     [0, 1] );

    Title = text (0.05, 0.5, 'Photoshop Program', 'fontsize', 20);

    ImgFrm = axes ( ...
    'position', [0.03, 0.2, 0.45, 0.6], ... 
    'xtick',    [], ... 
    'ytick',    [], ...
    'Visible','off',...
    'xlim',     [0, 1], ... 
    'ylim',     [0, 1] ...
    );

    ImgFrm2 = axes ( ...
    'position', [0.51, 0.2, 0.45, 0.6], ... 
    'xtick',    [], ... 
    'ytick',    [], ...
    'Visible','off',...
    'xlim',     [0, 1], ... 
    'ylim',     [0, 1] ...
    );

    ButtonFrm = uicontrol (MainFrm, ...
        'style',    'pushbutton', ... 
        'string',   'OPEN THE IMAGE', ...
        'units',    'normalized', ...
        'position', [0.1, 0.05, 0.20, 0.1], ... 
        'callback', {@loadImage, ImgFrm});
  
    ButtonFrm2 = uicontrol (MainFrm, ...
        'style',    'pushbutton', ... 
        'string',   'Threshold', ...
        'units',    'normalized', ...
        'position', [0.3, 0.05, 0.20, 0.1], ... 
        'callback', {@threshold,ImgFrm, ImgFrm2});
    
    ButtonFrm3 = uicontrol (MainFrm, ...
        'style',    'pushbutton', ... 
        'string',   'Negative', ...
        'units',    'normalized', ...
        'position', [0.5, 0.05, 0.20, 0.1], ... 
        'callback', {@negative,ImgFrm, ImgFrm2});
    
    ButtonFrm4 = uicontrol (MainFrm, ...
        'style',    'pushbutton', ... 
        'string',   'Blur', ...
        'units',    'normalized', ...
        'position', [0.7, 0.05, 0.20, 0.1], ... 
        'callback', {@blur,ImgFrm, ImgFrm2});
end

function threshold(~, ~, sourceAxes, targetAxes)
    thresholdValue = 128; 
    img = get(sourceAxes, 'Children').CData;
    output = (img > thresholdValue) * 255;
    imshow(output, 'Parent', targetAxes);
end

function negative(~, ~, sourceAxes, targetAxes)
img = get(sourceAxes, 'Children').CData;
output=255-img;
imshow(output, 'Parent', targetAxes);
end

function blur(~, ~, sourceAxes, targetAxes)
img = get(sourceAxes, 'Children').CData;
img=rgb2gray(img);
output=medfilt2(img,[10,10]);
imshow(output, 'Parent', targetAxes);
end